import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { getSession, useSession } from "next-auth/react";

export default function Home({ session }) {
  console.log(session);
  const name = session?.user.name.split(" ")[1];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.name}>
          {name ? "Hey" + " " + name + "," : ""} Welcome to next js
        </h1>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const { req } = context;
  let host = req.headers.host;
  const session = await getSession(context);
  console.log(session);

  if (!session) {
    return {
      redirect: {
        destination: "/login",
        // destination: `/api/auth/signin?callbackUrl=http://${host}/blog`,
        permanent: false,
      },
    };
  }

  return {
    props: {
      session,
    },
  };
}
